### ISSUE TITLE
Problem with schema URL validation when using URLS without a  TLD

### ISSUE THREAD

**Issue by ad-on-is** [adonisjs/env#33]
Just realized the following

`SOMEURL: Env.schema.string({format: 'url'})`

if the URL is something like `http://someservice:3030`, which is the case when using an AdonisJS application with other services and `docker-compose`, it throws an error.

`E_INVALID_ENV_VALUE: Value for environment variable "SOMEURL" must be a valid URL, instead received "http://someservice:3030"`

Expected result: `http://someservice:3030"` should be valid

**Comment by shiny** [comment]
I had the same problem, `http://127.0.0.1:3333` is a valid url but `http://localhost:3333` is not.
that's confusing.

**Comment by thetutlage** [comment]
This happens because the `http://localhost:3333` does not have a `tld` on it. Here's the docs to allow URLs without `tld` https://docs.adonisjs.com/guides/environment-variables#url.

Why does it allow `http://127.0.0.1:3333`? I am not sure, we use https://github.com/validatorjs/validator.js, so maybe there is some exception for IP Addresses to pass the validation rule.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
